services:
  pgvector:
    build:
      context: ./pgvector
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
  adminer:
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080
    restart: always

volumes:
  pgvector_data:
